---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar-event-source
spec:
  type: calendar
  calendar:
    example-calendar-interval:
      interval: 1m
      userPayload: {"message": "Hi! I am a Humpback whale!"}
    example-calendar-schedule:
      schedule: "*/1 * * * *"
      userPayload: {"message": "Greetings! I am a Killer whale!"}
...
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: calendar-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: dh-dev-argo
spec:
  replica: 1
  type: calendar
  eventSourceRef:
    name: calendar-event-source
  template:
    metadata:
      name: calendar-gateway
      labels:
        gateway-name: calendar-gateway
    spec:
      containers:
        - name: gateway-client
          image: argoproj/gateway-client:v0.14.0
          command: ["/bin/gateway-client"]
        - name: calendar-events
          image: argoproj/calendar-gateway:v0.14.0
          command: ["/bin/calendar-gateway"]
      serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://demo-sensor.dh-dev-argo.svc:9300/"
...
