---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-event-source
spec:
  type: kafka
  kafka:
    example-kafka:
      url: dev-kafka-bootstrap.dh-dev-message-bus:9092
      topic: argo-events-demo-topic
      jsonBody: true
      partition: "0"
      connectionBackoff:
        duration: 10000000000
        steps: 5
        factor: 2
        jitter: 0.2

...
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: kafka-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: odh-argo-demo
spec:
  replica: 1
  type: kafka
  eventSourceRef:
    name: kafka-event-source
  template:
    metadata:
      name: kafka-gateway
      labels:
        gateway-name: kafka-gateway
    spec:
      containers:
        - name: gateway-client
          image: argoproj/gateway-client:v0.14.0
          imagePullPolicy: Always
          command: ["/bin/gateway-client"]
        - name: kafka-events
          image: argoproj/kafka-gateway:v0.14.0
          imagePullPolicy: Always
          command: ["/bin/kafka-gateway"]
      serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://demo-sensor.odh-argo-demo.svc:9300/"
...
