---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-event-source
spec:
  type: kafka
  kafka:
    example-kafka:
      url: dev-kafka-bootstrap.dh-dev-message-bus.svc.cluster.local:9092
      topic: argo-events-demo-topic
      jsonBody: true
      partition: "all"
...
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: kafka-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: dh-dev-argo
spec:
  replica: 1
  type: kafka
  eventSourceRef:
    name: kafka-event-source
  template:
    metadata:
      name: kafka-gateway
      labels:
        gateway-name: kafka-gateway
    spec:
      containers:
        - name: gateway-client
          image: argoproj/gateway-client:v0.14.0
          command: ["/bin/gateway-client"]
        - name: kafka-events
          image: argoproj/kafka-gateway:v0.14.0
          command: ["/bin/kafka-gateway"]
      serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://demo-sensor.dh-dev-argo.svc:9300/"
...
